project_name: gowebly
report_sizes: true

env_files:
  github_token: ~/.github_token

before:
  hooks:
    - go mod download
    - go mod tidy
    - go run github.com/google/wire/cmd/wire@latest ./...
    - go run golang.org/x/vuln/cmd/govulncheck@latest -test ./...
    - go run github.com/google/osv-scanner/cmd/osv-scanner@latest -r .
    - go run github.com/securego/gosec/v2/cmd/gosec@latest -exclude=G204 -quiet ./...
    - go run github.com/go-critic/go-critic/cmd/gocritic@latest check -enableAll ./...
    - go run github.com/gordonklaus/ineffassign@latest ./...
    - go test -race ./...

builds:
  -
    id: default
    env: [ CGO_ENABLED=0 ]
    goos: [ linux, windows, darwin ]
    goarch: [ amd64, arm64 ]

upx:
  -
    ids: [ default ]
    enabled: true
    compress: best
    lzma: true
    brute: true
    goos: [ linux, windows ] # skip darwin (macOS 13.x Ventura is not supported now)
    goarch: [ amd64, arm64 ]

release:
  ids: [ default ]
  draft: true
  replace_existing_draft: true
  target_commitish: '{{ .Commit }}'
  prerelease: auto
  mode: replace
  header: |
    ## ✨ The {{ .ProjectName }} `{{ .Tag }}` release
    
    <img width="100%" alt="gowebly logo" src="https://github.com/gowebly/gowebly/assets/11155743/55c80da2-30c6-45e7-a813-1ddc42764480">
  footer: |    
    ## How to update?
    
    For native Go installation (any platforms):
    
    ```console
    go install github.com/gowebly/gowebly@latest
    ```
    
    For [Homebrew][brew_url] users (GNU/Linux, Apple macOS):
    
    ```console
    brew upgrade gowebly/tap/gowebly
    ```
    
    For [Docker][docker_url] users (any platforms):
    
    ```console
    docker pull gowebly/gowebly:latest
    ```
    
    For other ways (any platforms): manually download and re-install a ready-made package from the `Assets` section.
    
    > 💡 Note: See the [Complete user guide][gowebly_url] to get a general information.
    
    ## Your help to improve project
    
    We would be truly grateful for any help with:
    
    - Creating tests and benchmarks for code;
    - Improving existing functions, structs, or tests;
    - Feature requests with interesting functions that would be good to add.
    
    Your PRs & issues are welcome! Thanks 😉
    
    <!-- Links -->
    
    [brew_url]: https://brew.sh
    [docker_url]: https://www.docker.com
    [gowebly_url]: https://gowebly.org
  disable: false
  skip_upload: false

dockers:
  -
    id: '{{ .ProjectName }}'
    ids: [ default ]
    image_templates:
      - 'gowebly/{{ .ProjectName }}:latest'
      - 'gowebly/{{ .ProjectName }}:{{ .Tag }}'
      - 'gowebly/{{ .ProjectName }}:v{{ .Major }}'
      - 'gowebly/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}'
    build_flag_templates:
      - '--pull'
      - '--label=org.opencontainers.image.created={{ .Date }}'
      - '--label=org.opencontainers.image.title={{ .ProjectName }}'
      - '--label=org.opencontainers.image.revision={{ .FullCommit }}'
      - '--label=org.opencontainers.image.version={{ .Version }}'
      - '--platform=linux/amd64'
    skip_push: false
    push_flags:
      - '--tls-verify=false'

brews:
  -
    repository:
      owner: gowebly
      name: homebrew-tap
      branch: main
      token: '{{ .Env.GITHUB_TOKEN }}'
      pull_request:
        enabled: true
      git:
        url: 'git@github.com:gowebly/homebrew-tap.git'
        private_key: '{{ .Env.BREW_PRIVATE_KEY_PATH }}'
    commit_author:
      name: Vic Shóstak
      email: koddr.me@gmail.com
    commit_msg_template: 'Brew formula update for {{ .ProjectName }} version {{ .Tag }}'
    folder: Formula
    caveats: |
      After install, create a new project (with a default configuration):

      $ gowebly create
      
      💡 Note: See the Complete user guide (https://gowebly.org/) to get a general information.
    homepage: 'https://github.com/gowebly/{{ .ProjectName }}'
    description: |
      A next-generation CLI tool for building amazing web applications in Go using htmx & hyperscript and the most popular atomic/utility-first CSS frameworks.
    license: Apache 2.0
    skip_upload: false

nfpms:
  -
    maintainer: Vic Shóstak <koddr.me@gmail.com>
    description: |
      A next-generation CLI tool for building amazing web applications in Go using htmx & hyperscript and the most popular atomic/utility-first CSS frameworks.
    homepage: 'https://github.com/gowebly/{{ .ProjectName }}'
    license: Apache 2.0
    formats: [ deb, rpm, apk, archlinux ]

archives:
  -
    format_overrides:
      - goos: windows
        format: zip
    files: [ LICENSE, README.md ]

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  abbrev: -1
  filters:
    exclude: [ '^*.md', '^*.ya?ml' ]
  groups:
    - title: New features
      regexp: ^.*?((A|a)dd)|((F|f)eature).*?$
      order: 0
    - title: Bug fixes
      regexp: ^.*?((B|b)ug)|((F|f)ix).*?$
      order: 1
    - title: Improvements
      regexp: ^.*?(I|i)mprove.*?$
      order: 2
    - title: Updates
      regexp: ^.*?(U|u)pdate.*?$
      order: 3
    - title: Security issues
      regexp: ^.*?(S|s)ecurity.*?$
      order: 4
    - title: Delete unused or stale
      regexp: ^.*?((D|d)elete)|((U|u)nused)|((S|s)tale).*?$
      order: 5
    - title: Others
      order: 999
