# The 'backend' block sets a Go backend options.
# Required to set up.
backend:
  # 'module_name' (string) option can be any name of your Go module (for example, 'github.com/user/project')
  module_name: project
  # 'go_framework' (string) option can be one of the values: 'fiber', 'echo', 'chi', or 'default'
  go_framework: default
  # 'port' (int) option can be any port that is not taken up on your system
  port: 5000

  # The 'timeout' block sets a server options.
  # For more information, see https://blog.cloudflare.com/the-complete-guide-to-golang-net-http-timeouts/
  # Required to set up.
  timeout:
    # 'read' (int) option can be any number of seconds, 5 is recommended
    read: 5
    # 'write' (int) option can be any number of seconds, 10 is recommended
    write: 10

# The 'frontend' block sets a frontend options.
# Required to set up.
frontend:
  # 'package_name' (string) option can be any name of your package.json (for example, 'project')
  package_name: project
  # 'css_framework' (string) option can be one of the values: 'tailwindcss', 'unocss', or 'default'
  css_framework: default
  # 'runtime_environment' (string) option can be one of the values: 'bun', or 'default'
  runtime_environment: default
  # 'htmx' (string) option can be any existing version
  htmx: latest
  # 'hyperscript' (string) option can be any existing version
  hyperscript: latest

  # The 'manifest' block sets the PWA manifest options.
  # For more information, see https://developer.mozilla.org/en-US/docs/Web/Manifest
  # Optional to set up.
  manifest:
    # 'name' (string) option can be any name of your project
    name: project
    # 'short_name' (string) option can be any short name of your project
    short_name: project
    # 'description' (string) option can be any description of your project
    description: |
      Description of your project.
    # 'background_color' (string) option can be any HEX color
    background_color: '#FEFEF5'
    # 'theme_color' (string) option can be any HEX color
    theme_color: '#FEFEF5'
    # 'display' (string) option can be one of the values: 'fullscreen', 'standalone', 'minimal-ui', or 'browser'
    display: standalone
    # 'orientation' (string) option can be one of the values: 'landscape', 'landscape-primary', 'landscape-secondary',
    # 'portrait', 'portrait-primary', 'portrait-secondary', 'natural', or 'any'
    orientation: portrait
    # 'start_url' (string) option can be any URL path or dot ('.')
    start_url: .

    # The 'icons' block sets the PWA icons options.
    # For more information, see https://developer.mozilla.org/en-US/docs/Web/Manifest/icons
    # Required to set up, if you want to use PWA manifest.
    icons:
      -
        # 'src' (string) option can be any URL path relative to the manifest.json file,
        # e.g. 'favicons/manifest-touch-icon.svg', if manifest.json is in the same folder
        src: favicons/manifest-touch-icon.svg
        # 'type' (string) option can be one of the values: 'image/jpeg', 'image/png', 'image/svg+xml', or 'image/webp'
        type: image/svg+xml
        # 'sizes' (string) option can be any size of your icon (e.g. '128x128 256x256 512x512' or 'any' for SVG)
        sizes: any
